# permissions for end users to view zaynnginxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zaynnginx-viewer-role
rules:
- apiGroups:
  - zaynsolutions.com
  resources:
  - zaynnginxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - zaynsolutions.com
  resources:
  - zaynnginxes/status
  verbs:
  - get
